### PR TITLE
make socket debugging tool directly usable

### PR DESCRIPTION
**Pull request by jamesscottbrown**
Serve the socket debugigng page from OVE, and provide a link for
each section listed in the table on the landing page.

### CODE REVIEW

**Comment by senakafdo** [comment]
@jamesscottbrown, while it is convenient for someone who is interested in using this tool to find it listed under OVE core, I find that this has no functional requirement of being a part of the OVE distribution. It also would just become a security risk to keep this running by default. True that it exposes nothing more than what someone can do with the OVE APIs, but this code would run on the OVE host and will have direct/unrestricted access to the WebSockets.

This was the reason why I explicitly introduced it as an additional tool, stored it in its current location and documented how to use it, if someone wanted to.

**Comment by oserban** [comment]
@senakafdo @jamesscottbrown I would see this feature enabled in a debug build of OVE, if someone wants to spend some time to extend the build scripts I strongly encourage this ... 

Otherwise I agree with @senakafdo that we should not enable this feature in production builds

**Comment by jamesscottbrown** [comment]
>  I find that this has no functional requirement of being a part of the OVE distribution

Ease of access to debugging tools has a major effect on how efficiently problems can be identified and fixed. It also enables users to better understand how OVE works, by allowing them to see the messages that are being passed.

The current process for opening the debugging tool is not reasonable: it requires downloading a file, starting a web-server, and then constructing a URL by hand. This is an unnecessarily bad user experience.

> It also would just become a security risk to keep this running by default. True that it exposes nothing more than what someone can do with the OVE APIs, but this code would run on the OVE host and will have direct/unrestricted access to the WebSockets.

I don't understand: the JavaScript code runs entirely in the browser (*not* on the OVE Core backend), and it connects to the OVE core instance via a websocket *originating from the user's browser* and so can do the same things whether the script is being served by the OVE instance itself or a webserver running on the user's local machine. 

The security risk is the fact that anyone can connect to an OVE instance and perform any action with no authentication or authorization.

> @senakafdo @jamesscottbrown I would see this feature enabled in a debug build of OVE, if someone wants to spend some time to extend the build scripts I strongly encourage this ...

I don't entirely disagree. However, OVE currently fails frequently enough that we are often trying to debug something in the production environment (and if we want to figure out what weird state we've currently got into, then restarting into a separate debug build is undesirable), so I'm not sure if restricting debugging features to a separate build is helpful, unless they have a performance impact.

**Comment by jamesscottbrown** [comment]
As an additional observation, I don't think hosting the websocket debugging tool is any more dangerous than hosting a Swagger instance that lets users make arbitrary API calls, which we do by default.

**Comment by senakafdo** [comment]
> @senakafdo @jamesscottbrown I would see this feature enabled in a debug build of OVE, if someone wants to spend some time to extend the build scripts I strongly encourage this ...

Partly agree. If we have a debug-only build this kind of thing can be enabled. Partly disagree, because this is something seldom used and those who use it can simply run the tool by following the instructions provided.

> As an additional observation, I don't think hosting the websocket debugging tool is any more dangerous than hosting a Swagger instance that lets users make arbitrary API calls, which we do by default.

This tool lets you tap into the WebSockets from within the same domain which bypasses all CSRF checks. A REST API OTOH can be secured by installing a proxy infront of it.

**Comment by jamesscottbrown** [comment]
I still don't understand. The debug tool can connect to OVE and read or send messages over a websocket, regardless of where it is served from (this must be true, or else your suggestion that users host the debugging tool locally wouldn't work).

Generalising more, *any arbitrary javascript running in a browser* can interact with OVE over a websocket. There are no users, no authentication, and nothing to forge, so I'm not sure it's even meaningful to refer to CRSF.

IIUC, the websockets are already being proxied by nginx in the default installation (this is what the [`proxy_set_header Upgrade $http_upgrade;`](https://github.com/ove/ove-install/blob/6acadcb3077f8953412f59b9e8030ab5d4580050/templates/config/default.conf#L186) and `proxy_set_header Connection $connection_upgrade;` are for). In principle, nginx could be configured to restrict access to either the REST API or the socket; in the default installation, this isn't done and anyone can send any command from anywhere.

**Pull request closed without merging**
