### PR TITLE
Filtering

### PR DESCRIPTION
**Pull request by jamesscottbrown**
This PR creates a library that can be used by OVE Apps to implement filtering in a uniform way without code duplication.

It extracts the filtering code Senaka wrote for the networks app, adds support for some additional functions, replaces the odata-parser dependency with a new parser, and provides tests.

### CODE REVIEW

**Comment by senakafdo** [comment]
@jamesscottbrown, I have a question, when a user invokes the binary `substring` operation, would they now have to invoke it as `substring_binary`? or this is simply an internal terminology?

**Comment by jamesscottbrown** [comment]
> @jamesscottbrown, I have a question, when a user invokes the binary `substring` operation, would they now have to invoke it as `substring_binary`? or is this simply an internal terminology?

They would use it it in the same way as before (as in [this test](https://github.com/ove/ove/blob/2691c5824b8e1be955f804c6eb07b0acd81195af/packages/ove-lib-filter/test/core-functionality.test.js#L178)).

**Comment by senakafdo** [comment]
@jamesscottbrown are you looking into (a) creating a separate PR for the networks app migrating its implementation to this, and (b) extending the implementation to at least one other app such as charts or HTML? The PR is pending until we are able to prove that this functionality can be used in the existing networks app and also proving that it works on at least one other app. There is no value in merging this PR until that requirement is met.

**Comment by senakafdo** [comment]
@jamesscottbrown, I am closing this PR as we found no use of this functionality beyond what we do with it today. We can revisit this sometime later - if we have an actual requirement.

**Pull request closed without merging**
